proxy:
    domains:
        - template

workers:
    docker_compose: ~
    messenger_consume_async:
        cmd: [ 'symfony', 'console', 'messenger:consume', 'async' ]
    tailwind:
        cmd: [ 'symfony', 'console', 'tailwind:build', '--watch' ]
