services:
  mailpit:
    container_name: template-mailpit-dev
    image: 'axllent/mailpit:latest'
    ports:
      - '127.0.0.1:1027:1025'  # SMTP server
      - '127.0.0.1:8027:8025'  # Web UI
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:8025/readyz']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
